config:
  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*_demo_*.log
        multiline.parser  docker, cri
        Tag               kube.*
        Mem_Buf_Limit     5MB

  outputs: |
    [OUTPUT]
        Name                es
        Match               kube.*
        Host                elasticsearch.logging.svc.cluster.local
        Port                9200
        Logstash_Format     On
        Logstash_Prefix     k8s
        Suppress_Type_Name  On
        Replace_Dots        On
        Retry_Limit         False
